import Navbar from "../components/navbar";
import Subnavbar from "../components/subnavbar";
import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "merchant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="fixed w-full z-10">
          <Navbar />
          <Subnavbar />
        </main>
        <div>{children}</div>
      </body>
    </html>
  );
}
